name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
  TF_BACKEND_BUCKET_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - name: Install Winglang and dependencies
        run: |
          npm install -g winglang
          npm install

      - name: Cache Terraform Plugins
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Winglang Compile
        run: |
          wing compile -t tf-aws -t platform.static-backend.js main.w

      - name: Terraform Init
        working-directory: ./target/main.tfaws
        run: terraform init -reconfigure

      - name: Terraform Plan
        id: plan
        working-directory: ./target/main.tfaws
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./target/main.tfaws
        run: terraform apply -auto-approve